
branches:
  except:
  - master
  - experimental

language:
  - cpp

compiler:
  - clang

matrix:
  include:
    - os: linux
      sudo: required
      env:
        - USE_UPNP: ''
        - PIE: 1
        - DEPENDENCIES: |-
                         build-essential
                         libtool
                         automake
                         autotools-dev
                         autoconf
                         pkg-config
                         libssl-dev
                         libgmp3-dev
                         libevent-dev
                         bsdmainutils
                         libdb4.8-dev
                         libdb4.8++-dev
                         libminiupnpc-dev
    # - os: linux
    #   sudo: required
    #   env:
    #     - USE_UPNP: ''
    #     - PIE: 1
    #     - QT: qt5
    #     - MARTEX_QT: 1
    #     - MARTES_QT_QR: 1
  # - os: osx
  #   language: generic
  #   env: TOXENV=py32
  # - os: osx
  #   language: generic
  #   env: TOXENV=py33

before_install:
  - |-
    if [ $TRAVIS_OS_NAME == linux ]; then
      sudo add-apt-repository ppa:bitcoin/bitcoin -y &&
      sudo apt-get update;
    fi
# script:
#   - |-
#     if [ $TRAVIS_OS_NAME == linux && $MARTEX_QT == 1]; then
#       ./.travis/build-unix.sh;
#     fi

install:
  - |-
    if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-get -y install $DEPENDENCIES;
    fi


script:
  - |-
    if [ $TRAVIS_OS_NAME == linux ]; then ./.travis/build-unix.sh; fi

